language: en
pipeline:
- name: WhitespaceTokenizer
  case_sensitive: false
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
